// <auto-generated />
using System;
using DatabaseLayer.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DatabaseLayer.Migrations
{
    [DbContext(typeof(TimeControllerContext))]
    [Migration("20240608135808_hotfixx3")]
    partial class hotfixx3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DatabaseLayer.Database.Models.Access", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("EmployeeID")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TradePointID")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TradePointID");

                    b.ToTable("Accesess");
                });

            modelBuilder.Entity("DatabaseLayer.Database.Models.Employee", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AccessId")
                        .HasColumnType("uuid");

                    b.Property<int>("GenderID")
                        .HasColumnType("integer");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Patronymic")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<string>("Surname")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.HasIndex("AccessId");

                    b.HasIndex("GenderID");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("DatabaseLayer.Database.Models.Gender", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Genders");
                });

            modelBuilder.Entity("DatabaseLayer.Database.Models.ShiftStory", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ComeDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EmployeeID")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LeaveDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TradePointID")
                        .HasColumnType("uuid");

                    b.HasKey("ID");

                    b.HasIndex("EmployeeID");

                    b.HasIndex("TradePointID");

                    b.ToTable("ShiftStories");
                });

            modelBuilder.Entity("DatabaseLayer.Database.Models.TradePoint", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("PointName")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("TradePoints");
                });

            modelBuilder.Entity("DatabaseLayer.Database.Models.Access", b =>
                {
                    b.HasOne("DatabaseLayer.Database.Models.TradePoint", "TradePoint")
                        .WithMany("Accesses")
                        .HasForeignKey("TradePointID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TradePoint");
                });

            modelBuilder.Entity("DatabaseLayer.Database.Models.Employee", b =>
                {
                    b.HasOne("DatabaseLayer.Database.Models.Access", "Access")
                        .WithMany("Employees")
                        .HasForeignKey("AccessId");

                    b.HasOne("DatabaseLayer.Database.Models.Gender", "Gender")
                        .WithMany("Employees")
                        .HasForeignKey("GenderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Access");

                    b.Navigation("Gender");
                });

            modelBuilder.Entity("DatabaseLayer.Database.Models.ShiftStory", b =>
                {
                    b.HasOne("DatabaseLayer.Database.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DatabaseLayer.Database.Models.TradePoint", "TradePoint")
                        .WithMany()
                        .HasForeignKey("TradePointID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("TradePoint");
                });

            modelBuilder.Entity("DatabaseLayer.Database.Models.Access", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("DatabaseLayer.Database.Models.Gender", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("DatabaseLayer.Database.Models.TradePoint", b =>
                {
                    b.Navigation("Accesses");
                });
#pragma warning restore 612, 618
        }
    }
}
